name: portfolio
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  url_strategy: ^0.2.0
  firebase_core: ^2.5.0
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.1.10
dev_dependencies:
  flutter_test:
    sdk: flutter

  #flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
  
  fonts:
    - family:  PublicPixel
      fonts:
        - asset: assets/fonts/PublicPixel.ttf